### ISSUE TITLE
support for vertical segment

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/apsara#14]
We are having a design requirement that renders key-value pair vertically as example below:

<img width="333" alt="Screen Shot 2021-12-08 at 15 07 24" src="https://user-images.githubusercontent.com/5003439/145171710-b4dd421a-4580-42d8-97da-d32c158c72ae.png">

I think this use case is generic enough to be added as one variant for Segment component

**Comment by ravisuhag** [comment]
Closed as we have moved away from Ant system
