### ISSUE TITLE
Segment value to accept `ReactNode` instead of `string` only

### ISSUE THREAD

**Issue by rahmatrhd** [odpf/apsara#15]
Currently, we're unable to achieve this using `Segment` component because `value` in `SegmentRowsProps` is only accepting string value.

<img width="275" alt="Screen Shot 2021-12-08 at 15 12 46" src="https://user-images.githubusercontent.com/5003439/145172418-e305eece-c91b-42f4-8ebf-8b995ba6fa6d.png">

Suggesting to allow `ReactNode` to be passed as a `value`

**Comment by ravisuhag** [comment]
Closed as we have moved away from Ant system
