### ISSUE TITLE
combobox for multiselect and search feature

### ISSUE THREAD

**Issue by akula-koteswarudu** [odpf/apsara#31]
**Summary**
- Radix select component doesn't provide multiselect and search features so we need to build a new multiselect component that provides these features.

**Proposed solution**
- we can use RC-SELECT from react-component library which comes with zero styling , to build combobox.

**Additional context**
- Antd select component will be replaced with radix select which doesn't provide required features .so we need build combobox.

**Comment by ravisuhag** [comment]
Closed as we have moved away from Ant system
